/**
 * Matriz de permisos por rol (F3-05).
 * Extraído de rbacConstants.js para respetar límite arquitectónico.
 */
import { ROLES, PERMISOS } from './rbacConstantsBase'

export const PERMISOS_POR_ROL = {
  [ROLES.ADMIN]: [
    PERMISOS.VER_FINANZAS, PERMISOS.VER_REPORTES, PERMISOS.VER_CONFIGURACION,
    PERMISOS.VER_INVENTARIO, PERMISOS.VER_LABORATORIO, PERMISOS.VER_ESTERILIZACION,
    PERMISOS.EDITAR_PRECIOS, PERMISOS.ELIMINAR_PACIENTES,
    PERMISOS.VER_HISTORIA_CLINICA_COMPLETA, PERMISOS.GESTIONAR_USUARIOS,
    PERMISOS.VER_LOGS_SISTEMA, PERMISOS.VER_VADEMECUM,
    PERMISOS.ADMINISTRAR_VADEMECUM, PERMISOS.VER_PAPELERA,
    PERMISOS.VACIAR_PAPELERA
  ],
  [ROLES.DENTISTA]: [
    PERMISOS.VER_FINANZAS, PERMISOS.VER_REPORTES, PERMISOS.VER_INVENTARIO,
    PERMISOS.VER_LABORATORIO, PERMISOS.VER_ESTERILIZACION, PERMISOS.EDITAR_PRECIOS,
    PERMISOS.ELIMINAR_PACIENTES, PERMISOS.VER_HISTORIA_CLINICA_COMPLETA,
    PERMISOS.VER_VADEMECUM, PERMISOS.ADMINISTRAR_VADEMECUM
  ],
  [ROLES.ASISTENTE]: [
    PERMISOS.VER_INVENTARIO, PERMISOS.VER_LABORATORIO,
    PERMISOS.VER_ESTERILIZACION, PERMISOS.VER_HISTORIA_CLINICA_COMPLETA,
    PERMISOS.VER_VADEMECUM
  ],
  [ROLES.RECEPCION]: []
}
